/// Flutter icons PAPUF
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PAPUF
///      fonts:
///       - asset: fonts/PAPUF.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class PAPUF {
  PAPUF._();

  static const _kFontFam = 'PAPUF';

  static const IconData home_outline = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData gauge = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chart_bar_outline = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData user_outline = IconData(0xe804, fontFamily: _kFontFam);
}
